import 'conversation_intent.dart';

/// High-value, data-only conversational intents. Adding coverage means adding
/// a row here; matching and UI code remain unchanged.
final List<ConversationIntentDefinition> conversationIntentCatalog =
    <ConversationIntentDefinition>[
  // Compliments (18)
  _i('compliment_eyes', 'Compliments eyes, eye colour, or gaze',
      ['目の色が綺麗', '目きれいだね', 'Your eyes are beautiful'],
      ['目', '瞳', '目の色', '綺麗', '素敵', '印象的'], ConversationFunction.compliment,
      {'compliments', 'eyes'}, priority: 92),
  _i('compliment_smile', 'Compliments a smile',
      ['笑顔が素敵', '笑った顔かわいい', 'You have a nice smile'],
      ['笑顔', '笑った顔', 'スマイル', '素敵'], ConversationFunction.compliment,
      {'compliments', 'smile'}, priority: 88),
  _i('compliment_face', 'Compliments facial appearance',
      ['顔が綺麗', '整った顔してる', 'You have a beautiful face'],
      ['顔', '綺麗', '美人', '整って'], ConversationFunction.compliment,
      {'compliments', 'appearance'}),
  _i('compliment_hair', 'Compliments hair or hairstyle',
      ['髪きれい', 'その髪型似合う', 'I like your hair'],
      ['髪', '髪型', 'ヘア', '似合う'], ConversationFunction.compliment,
      {'compliments', 'hair'}),
  _i('compliment_height', 'Comments positively on height',
      ['背高いね', 'スタイルいいね', 'You are tall'],
      ['背', '身長', '高い', 'スタイル'], ConversationFunction.compliment,
      {'compliments', 'height'}),
  _i('compliment_clothes', 'Compliments clothing',
      ['その服似合う', '服おしゃれだね', 'I like your outfit'],
      ['服', '洋服', 'コーデ', '似合う'], ConversationFunction.compliment,
      {'compliments', 'clothes', 'fashion'}),
  _i('compliment_style', 'Compliments personal style',
      ['おしゃれだね', 'センスいいね', 'You have great style'],
      ['おしゃれ', 'センス', 'スタイル', '格好いい'], ConversationFunction.compliment,
      {'compliments', 'fashion'}),
  _i('compliment_voice', 'Compliments speaking voice',
      ['声がいいね', '声落ち着く', 'You have a nice voice'],
      ['声', '話し方', '落ち着く', '素敵'], ConversationFunction.compliment,
      {'compliments', 'voice'}),
  _i('compliment_japanese', 'Compliments Japanese ability',
      ['日本語上手', '日本語うまいね', 'Your Japanese is good'],
      ['日本語', '上手', 'うまい', '話せる'], ConversationFunction.compliment,
      {'compliments', 'language', 'japanese'}, priority: 90),
  _i('compliment_english', 'Compliments English ability',
      ['英語上手', '英語うまいね', 'Your English is good'],
      ['英語', '上手', 'うまい', '発音'], ConversationFunction.compliment,
      {'compliments', 'language', 'english'}),
  _i('compliment_personality', 'Compliments personality',
      ['性格いいね', 'いい性格してる', 'I like your personality'],
      ['性格', '人柄', 'いい人', '好き'], ConversationFunction.compliment,
      {'compliments', 'personality'}),
  _i('compliment_kindness', 'Calls the user kind',
      ['優しいね', '本当に親切', 'You are kind'],
      ['優しい', '親切', '気遣い', 'いい人'], ConversationFunction.compliment,
      {'compliments', 'kindness'}),
  _i('compliment_funny', 'Calls the user funny',
      ['面白いね', '本当に笑える', 'You are funny'],
      ['面白い', '笑える', 'ユーモア', '楽しい'], ConversationFunction.compliment,
      {'compliments', 'humor'}),
  _i('compliment_young', 'Says the user looks young',
      ['若く見える', '年齢より若いね', 'You look young'],
      ['若い', '若く見える', '年齢', '見えない'], ConversationFunction.compliment,
      {'compliments', 'age'}),
  _i('compliment_cool', 'Calls the user cool or handsome',
      ['格好いいね', 'イケメンだね', 'You look cool'],
      ['格好いい', 'イケメン', 'クール', '素敵'], ConversationFunction.compliment,
      {'compliments', 'appearance'}),
  _i('compliment_cute', 'Calls the user cute',
      ['かわいいね', 'ちょっとかわいい', 'You are cute'],
      ['かわいい', 'キュート', '愛嬌', '素敵'], ConversationFunction.compliment,
      {'compliments', 'appearance'}),
  _i('compliment_scent', 'Compliments fragrance or scent',
      ['いい匂いする', '香水いいね', 'You smell nice'],
      ['匂い', '香り', '香水', 'いい匂い'], ConversationFunction.compliment,
      {'compliments', 'scent'}),
  _i('compliment_body', 'Compliments physique or fitness',
      ['いい体してる', '鍛えてるね', 'You look fit'],
      ['体', '筋肉', '鍛えて', 'スタイル'], ConversationFunction.compliment,
      {'compliments', 'fitness'}),

  // Personal questions (20)
  _q('ask_origin', 'Asks where the user is from',
      ['どこ出身ですか', 'どこの国から来たの', 'Where are you from'],
      ['どこ', '出身', '国', 'から来た'], {'origin', 'travel'}),
  _q('ask_age', 'Asks the user age',
      ['何歳ですか', '年齢いくつ', 'How old are you'],
      ['年齢', '歳', 'いくつ', '若い'], {'age'}),
  _q('ask_residence', 'Asks where the user lives',
      ['どこに住んでる', 'この辺に住んでるの', 'Where do you live'],
      ['どこ', '住んで', '住まい', 'この辺'], {'location'}),
  _q('ask_job', 'Asks what the user does for work',
      ['仕事何してる', '何の仕事ですか', 'What do you do for work'],
      ['仕事', '職業', '働いて', '何してる'], {'work'}),
  _q('ask_time_in_japan', 'Asks how long the user has been in Japan',
      ['日本にどのくらいいるの', '日本に来て何年', 'How long in Japan'],
      ['日本', 'どのくらい', '何年', '来て'], {'japanese', 'travel'},
      priority: 96),
  _q('ask_reason_japan', 'Asks why the user came to Japan',
      ['なんで日本に来たの', '日本に来た理由は', 'Why did you come to Japan'],
      ['日本', 'なんで', '理由', '来た'], {'japanese', 'travel'}),
  _q('ask_relationship_status', 'Asks if the user has a partner',
      ['彼女いるの', '恋人いますか', 'Do you have a girlfriend'],
      ['彼女', '彼氏', '恋人', 'いる'], {'relationships', 'dating'},
      priority: 95),
  _q('ask_married', 'Asks if the user is married',
      ['結婚してるの', '既婚ですか', 'Are you married'],
      ['結婚', '既婚', '奥さん', '旦那'], {'relationships', 'marriage'}),
  _q('ask_type', 'Asks romantic type or preferences',
      ['どんな人がタイプ', '好きなタイプは', 'What is your type'],
      ['タイプ', 'どんな人', '好み', '好き'], {'relationships', 'preferences'}),
  _q('ask_weekend_plans', 'Asks what the user does this weekend',
      ['今週末何してる', '週末の予定は', 'What are you doing this weekend'],
      ['今週末', '週末', '予定', '何してる'], {'weekend', 'availability'},
      priority: 94),
  _q('ask_hobbies', 'Asks about hobbies',
      ['趣味は何', '休みの日何してる', 'What are your hobbies'],
      ['趣味', '休みの日', '好きなこと', '何してる'], {'hobbies'}),
  _q('ask_drink', 'Asks whether or what the user drinks',
      ['お酒飲む', '何飲むの', 'Do you drink'],
      ['お酒', '飲む', '何飲む', 'ビール'], {'drinks'}),
  _q('ask_music', 'Asks about music taste',
      ['どんな音楽好き', '何聴くの', 'What music do you like'],
      ['音楽', '曲', '聴く', '好き'], {'music'}),
  _q('ask_anime', 'Asks about anime',
      ['アニメ見る', '好きなアニメは', 'What anime do you watch'],
      ['アニメ', '見る', '作品', '好き'], {'anime', 'hobbies'}),
  _q('ask_food', 'Asks about favourite food',
      ['好きな食べ物は', '何食べたい', 'What food do you like'],
      ['食べ物', '料理', '何食べ', '好き'], {'food'}),
  _q('ask_languages', 'Asks which languages the user speaks',
      ['何語話せる', '日本語以外も話す', 'What languages do you speak'],
      ['言語', '何語', '話せる', '日本語'], {'language'}),
  _q('ask_family', 'Asks about family or siblings',
      ['兄弟いる', '家族はどこ', 'Do you have siblings'],
      ['兄弟', '姉妹', '家族', 'いる'], {'family'}),
  _q('ask_name', 'Asks the user name',
      ['名前は何', 'なんて呼べばいい', 'What is your name'],
      ['名前', '呼べば', 'なんていう', 'お名前'], {'introduction'}),
  _q('ask_birthday', 'Asks about birthday or zodiac',
      ['誕生日いつ', '何座ですか', 'When is your birthday'],
      ['誕生日', '何月', '星座', 'いつ'], {'birthday'}),
  _q('ask_social_media', 'Asks for social media or contact',
      ['インスタやってる', '連絡先交換しない', 'Do you have Instagram'],
      ['インスタ', '連絡先', '交換', 'SNS'], {'contact', 'dating'}),

  // Reactions (12)
  _r('reaction_amazing', 'Expresses amazement', ['すごい', 'すごいね', 'Amazing'],
      ['すごい', 'さすが', '最高'], {'reaction'}),
  _r('reaction_funny', 'Finds something funny',
      ['面白い', '笑える', 'That is funny'],
      ['面白い', '笑える', 'ウケる'], {'humor'}),
  _r('reaction_really', 'Questions whether something is true',
      ['本当に', 'マジで', 'Really'], ['本当', 'マジ', 'ほんと'], {'reaction'}),
  _r('reaction_surprised', 'Expresses surprise',
      ['びっくりした', '驚いた', 'I am surprised'],
      ['びっくり', '驚いた', '意外'], {'surprise'}),
  _r('reaction_unexpected', 'Says something was unexpected',
      ['意外だね', 'そう見えない', 'That is unexpected'],
      ['意外', '見えない', '予想外'], {'surprise'}),
  _r('reaction_scary', 'Calls something scary',
      ['怖い', 'ちょっと怖い', 'That is scary'],
      ['怖い', '恐い', 'びびる'], {'reaction'}),
  _r('reaction_cute', 'Calls an action or thing cute',
      ['かわいい', 'それかわいい', 'So cute'],
      ['かわいい', '愛嬌', 'キュート'], {'compliments'}),
  _r('reaction_cool', 'Calls something cool',
      ['格好いい', 'それいいね', 'That is cool'],
      ['格好いい', 'クール', 'いいね'], {'compliments'}),
  _r('reaction_kind', 'Calls an action kind',
      ['優しい', '優しいね', 'That is kind'],
      ['優しい', '親切', '気遣い'], {'kindness'}),
  _r('reaction_interesting_person', 'Calls user interesting',
      ['面白い人だね', '変わってて面白い', 'You are interesting'],
      ['面白い人', '興味深い', '変わって'], {'personality'}),
  _r('reaction_nice', 'Positive acknowledgement', ['いいね', 'それいい', 'Nice'],
      ['いいね', 'いい感じ', '素敵'], {'agreement'}),
  _r('reaction_doubt', 'Expresses doubt',
      ['怪しい', '信じられない', 'Sounds suspicious'],
      ['怪しい', '信じられない', 'ほんと'], {'doubt'}),

  // Invitations and availability (10)
  _v('invite_go_next_time', 'Invites user to go somewhere next time',
      ['今度行こう', '次一緒に行かない', 'Let us go next time'],
      ['今度', '行こう', '一緒に', '次'], {'invitation'}),
  _v('invite_drink_again', 'Invites user to drink again',
      ['また飲もう', '今度飲みに行こう', 'Let us drink again'],
      ['また', '飲もう', '飲みに', '今度'], {'invitation', 'drinks'},
      priority: 93),
  _v('ask_free_day', 'Asks whether user has a free day',
      ['暇な日ある', 'いつ空いてる', 'When are you free'],
      ['暇', '空いて', '予定', 'いつ'], {'availability'}),
  _v('ask_tomorrow_plans', 'Asks tomorrow plans',
      ['明日何してる', '明日暇', 'What are you doing tomorrow'],
      ['明日', '何してる', '暇', '予定'], {'availability'}),
  _v('ask_weekend_free', 'Asks if user is free this weekend',
      ['今週末空いてる', '週末暇ですか', 'Are you free this weekend'],
      ['今週末', '週末', '空いて', '暇'], {'weekend', 'availability'}),
  _v('invite_meet_again', 'Says they want to meet again',
      ['また会いたい', 'また会おう', 'I want to see you again'],
      ['また', '会いたい', '会おう', '次'], {'invitation', 'dating'}),
  _v('invite_go_together', 'Wants to go together',
      ['一緒に行きたい', '一緒に行こう', 'I want to go together'],
      ['一緒に', '行きたい', '行こう', '二人'], {'invitation'}),
  _v('invite_somewhere', 'Suggests going somewhere',
      ['どこか行こう', 'このあとどこか行く', 'Shall we go somewhere'],
      ['どこか', '行こう', 'このあと', '一緒に'], {'invitation'}),
  _v('invite_food', 'Invites user to eat',
      ['ご飯行こう', '何か食べに行かない', 'Want to get food'],
      ['ご飯', '食べに', '行こう', '一緒に'], {'invitation', 'food'}),
  _v('invite_karaoke', 'Invites user to karaoke',
      ['カラオケ行こう', '歌いに行かない', 'Want to do karaoke'],
      ['カラオケ', '歌い', '行こう', '一緒に'], {'invitation', 'music'}),

  // Hesitation and soft rejection (8)
  _x('soft_reject_busy', 'Says they are busy',
      ['忙しい', '最近忙しくて', 'I am busy'],
      ['忙しい', '時間ない', '仕事', '最近'], {'rejection'}),
  _x('soft_reject_next_time', 'Defers until next time',
      ['また今度', '今度にしよう', 'Maybe next time'],
      ['また今度', '今度', '次回', '今日は'], {'rejection'}),
  _x('soft_reject_schedule_unknown', 'Does not know schedule',
      ['予定わからない', 'まだ予定見えない', 'I do not know my schedule'],
      ['予定', 'わからない', '未定', 'まだ'], {'rejection', 'availability'}),
  _x('soft_reject_difficult', 'Says it is difficult',
      ['ちょっと難しい', 'それは難しいかな', 'That is difficult'],
      ['難しい', 'ちょっと', '無理', '厳しい'], {'rejection'}),
  _x('soft_reject_think', 'Asks for time to think',
      ['考えとく', 'ちょっと考える', 'Let me think'],
      ['考える', '考えとく', 'ちょっと', 'あとで'], {'rejection'}),
  _x('soft_reject_contact_later', 'Says they will contact later',
      ['また連絡する', 'あとで連絡するね', 'I will message you'],
      ['連絡', 'また', 'あとで', 'する'], {'rejection', 'contact'}),
  _x('soft_reject_not_today', 'Declines for today',
      ['今日は無理', '今日ちょっと無理', 'Not today'],
      ['今日', '無理', '難しい', 'ごめん'], {'rejection'}),
  _x('soft_reject_tired', 'Says they are tired',
      ['疲れてる', '今日は疲れた', 'I am tired'],
      ['疲れ', '眠い', '今日は', '休みたい'], {'rejection'}),

  // Teasing (8)
  _t('tease_popular', 'Teases that user seems popular',
      ['モテそう', '女慣れしてそう', 'You look popular'],
      ['モテそう', '女慣れ', '人気', '遊んで'], {'teasing', 'dating'}, priority: 89),
  _t('tease_charmer', 'Calls user smooth or charming',
      ['チャラそう', '口がうまいね', 'You are smooth'],
      ['チャラ', '口がうまい', '慣れて', '上手'], {'teasing'}),
  _t('tease_player', 'Suggests user is a player',
      ['遊んでそう', '女の子多そう', 'You seem like a player'],
      ['遊んで', '女の子', '慣れて', 'モテ'], {'teasing', 'dating'}),
  _t('tease_liar', 'Playfully calls user a liar',
      ['嘘ついてそう', '絶対嘘', 'You are lying'],
      ['嘘', '信じない', '怪しい', '絶対'], {'teasing'}),
  _t('tease_weird', 'Calls user strange',
      ['変だね', 'ちょっと変わってる', 'You are weird'],
      ['変', '変わって', '不思議', '面白い'], {'teasing'}),
  _t('tease_pickup', 'Accuses user of hitting on them',
      ['ナンパしてるでしょ', 'これナンパ', 'Are you hitting on me'],
      ['ナンパ', '口説いて', '声かけ', 'いつも'], {'teasing', 'dating'}),
  _t('tease_says_to_everyone', 'Says user tells everyone that',
      ['誰にでも言ってそう', 'みんなに言ってるでしょ', 'You say that to everyone'],
      ['誰にでも', 'みんな', '言ってる', 'いつも'], {'teasing'}),
  _t('tease_confident', 'Teases user confidence',
      ['自信あるね', '自信満々だね', 'You are confident'],
      ['自信', '自信満々', '強気', '余裕'], {'teasing', 'confidence'}),

  // Relationship and dating (10)
  _q('ask_older_preference', 'Asks if user likes older partners',
      ['年上好き', '年上はどう', 'Do you like older people'],
      ['年上', '好き', 'タイプ', '恋愛'], {'dating', 'preferences'}),
  _q('ask_younger_preference', 'Asks if user likes younger partners',
      ['年下好き', '年下はどう', 'Do you like younger people'],
      ['年下', '好き', 'タイプ', '恋愛'], {'dating', 'preferences'}),
  _q('ask_dated_foreigner', 'Asks about dating foreigners',
      ['外国人と付き合ったことある', '国際恋愛したことある', 'Dated a foreigner'],
      ['外国人', '付き合った', '国際恋愛', 'ことある'], {'dating'}),
  _q('ask_want_marriage', 'Asks if user wants marriage',
      ['結婚したい', '将来結婚したいですか', 'Do you want to marry'],
      ['結婚', 'したい', '将来', 'いつか'], {'relationships', 'marriage'}),
  _q('ask_in_love', 'Asks if user falls in love',
      ['恋愛してる', '好きな人いる', 'Are you in love'],
      ['恋愛', '好きな人', '恋して', 'いる'], {'relationships'}),
  _q('ask_are_popular', 'Asks if user is popular',
      ['モテるでしょ', '人気あるでしょ', 'Are you popular'],
      ['モテる', '人気', '女の子', 'でしょ'], {'dating', 'teasing'}),
  _q('ask_first_date', 'Asks ideal first date',
      ['初デート何したい', '理想のデートは', 'Ideal first date'],
      ['初デート', '理想', 'デート', '何したい'], {'dating'}),
  _q('ask_long_distance', 'Asks about long distance',
      ['遠距離恋愛できる', '遠距離はあり', 'Could you do long distance'],
      ['遠距離', '恋愛', 'できる', 'あり'], {'relationships'}),
  _q('ask_love_at_first_sight', 'Asks about love at first sight',
      ['一目惚れする', '一目惚れしたことある', 'Love at first sight'],
      ['一目惚れ', '恋', 'したこと', '信じる'], {'relationships', 'dating'}),
  _q('ask_kiss_preference', 'Asks about kissing preferences',
      ['キス好き', 'どんなキスが好き', 'Do you like kissing'],
      ['キス', '好き', 'どんな', '恋愛'], {'kissing', 'preferences'}),

  // Conversation continuation (6)
  _c('continue_i_see', 'Acknowledges with I see',
      ['そうなんだ', 'へえそうなんだ', 'I see'],
      ['そうなんだ', 'へえ', 'なるほど'], {'continuation'}),
  _c('continue_really', 'Invites elaboration with really',
      ['へえ', 'ほんと', 'Oh really'],
      ['へえ', 'ほんと', 'そうなの'], {'continuation'}),
  _c('continue_understand', 'Signals understanding',
      ['なるほど', 'わかる', 'I understand'],
      ['なるほど', 'わかる', '確かに'], {'continuation'}),
  _c('continue_agree', 'Agrees with the user', ['確かに', 'そうだね', 'Exactly'],
      ['確かに', 'そうだね', '同感'], {'agreement'}),
  _c('continue_sounds_fun', 'Says something sounds fun',
      ['楽しそう', 'それ面白そう', 'Sounds fun'],
      ['楽しそう', '面白そう', 'いいね'], {'interest'}),
  _c('continue_curious', 'Says something is intriguing',
      ['それ気になる', 'もっと聞きたい', 'I am curious'],
      ['気になる', '聞きたい', 'もっと'], {'interest'}),

  // Work and school (6)
  _q('ask_today_work', 'Asks whether user works today',
      ['今日は仕事', '今日働いてるの', 'Are you working today'],
      ['今日', '仕事', '働いて', '休み'], {'work'}),
  _q('ask_busy_work', 'Asks if work is busy',
      ['仕事忙しい', '最近仕事どう', 'Is work busy'],
      ['仕事', '忙しい', '最近', '大変'], {'work'}),
  _q('ask_student', 'Asks if user is a student',
      ['学生ですか', '大学生', 'Are you a student'],
      ['学生', '大学', '学校', '勉強'], {'school'}),
  _q('ask_study_subject', 'Asks what user studies',
      ['何勉強してる', '専攻は何', 'What do you study'],
      ['勉強', '専攻', '学部', '何'], {'school'}),
  _q('ask_enjoy_work', 'Asks if user likes work',
      ['仕事楽しい', '今の仕事好き', 'Do you enjoy work'],
      ['仕事', '楽しい', '好き', '今の'], {'work'}),
  _q('ask_tomorrow_work', 'Asks if user works tomorrow',
      ['明日仕事', '明日働くの', 'Do you work tomorrow'],
      ['明日', '仕事', '働く', '休み'], {'work', 'availability'}),

  // Location (6)
  _q('ask_neighborhood', 'Asks whether user lives nearby',
      ['この辺住んでる', '近くに住んでるの', 'Do you live nearby'],
      ['この辺', '近く', '住んで', '家'], {'location'}),
  _q('ask_visit_tenjin', 'Asks if user often visits this area',
      ['天神よく行く', 'この辺よく来る', 'Do you come here often'],
      ['天神', 'この辺', 'よく来る', '行く'], {'location'}),
  _q('ask_know_area', 'Asks if user knows an area',
      ['西新知ってる', 'この場所知ってる', 'Do you know this area'],
      ['知ってる', '場所', 'この辺', '行った'], {'location'}),
  _q('ask_first_time_here', 'Asks if it is first visit',
      ['ここ初めて', 'この店初めてですか', 'First time here'],
      ['ここ', '初めて', '店', '来た'], {'location'}),
  _q('ask_next_destination', 'Asks where user will go next',
      ['次どこ行く', 'このあとどこ行くの', 'Where are you going next'],
      ['次', 'このあと', 'どこ', '行く'], {'location', 'availability'}),
  _q('ask_favorite_place', 'Asks favourite local place',
      ['この辺で好きな店ある', 'おすすめの場所は', 'Favourite place nearby'],
      ['好きな店', 'おすすめ', '場所', 'この辺'], {'location'}),

  // Food and drinking (6)
  _q('ask_alcohol_tolerance', 'Asks if user handles alcohol',
      ['お酒強い', 'どのくらい飲める', 'Can you handle alcohol'],
      ['お酒', '強い', '飲める', '酔う'], {'drinks'}),
  _q('ask_drink_choice', 'Asks what user drinks',
      ['何飲む', 'いつも何飲むの', 'What do you drink'],
      ['何飲む', 'お酒', 'ビール', 'ワイン'], {'drinks'}),
  _q('ask_hungry', 'Asks if user is hungry',
      ['お腹すいた', '何か食べたい', 'Are you hungry'],
      ['お腹', '食べたい', '空いた', 'ご飯'], {'food'}),
  _q('ask_food_now', 'Asks what user wants to eat',
      ['何食べたい', '今何食べたい', 'What do you want to eat'],
      ['何食べ', '食べたい', '今', '料理'], {'food'}),
  _q('ask_spicy_food', 'Asks about spicy food',
      ['辛いもの大丈夫', '辛い料理好き', 'Do you like spicy food'],
      ['辛い', '料理', '大丈夫', '好き'], {'food'}),
  _q('ask_sweets', 'Asks about sweets',
      ['甘いもの好き', 'デザート食べる', 'Do you like sweets'],
      ['甘い', 'スイーツ', 'デザート', '好き'], {'food'}),

  // Interests (10)
  _q('ask_games', 'Asks about video games',
      ['ゲームする', '何のゲーム好き', 'Do you game'],
      ['ゲーム', '遊ぶ', '好き', '何の'], {'games', 'hobbies'}),
  _q('ask_movies', 'Asks about movies',
      ['映画見る', '好きな映画は', 'What movies do you like'],
      ['映画', '見る', '作品', '好き'], {'movies', 'hobbies'}),
  _q('ask_karaoke', 'Asks about karaoke',
      ['カラオケ行く', '何歌うの', 'Do you like karaoke'],
      ['カラオケ', '歌う', '曲', '行く'], {'music', 'hobbies'}),
  _q('ask_sports', 'Asks about sports',
      ['スポーツする', '何か運動してる', 'Do you play sports'],
      ['スポーツ', '運動', 'ジム', 'する'], {'fitness', 'hobbies'}),
  _q('ask_travel', 'Asks about travel',
      ['旅行好き', '最近どこか行った', 'Do you like travel'],
      ['旅行', '旅', '海外', '行った'], {'travel', 'hobbies'}),
  _q('ask_korea', 'Asks about Korea',
      ['韓国行ったことある', '韓国好き', 'Have you been to Korea'],
      ['韓国', '行った', '好き', 'ソウル'], {'travel', 'korea'}),
  _q('ask_overseas', 'Asks about overseas travel',
      ['海外よく行く', 'どの国行った', 'Do you travel abroad'],
      ['海外', '国', '旅行', '行った'], {'travel'}),
  _q('ask_fashion', 'Asks about fashion',
      ['服好き', 'どこで服買う', 'Are you into fashion'],
      ['服', 'ファッション', '買う', 'ブランド'], {'fashion', 'hobbies'}),
  _q('ask_pets', 'Asks about pets',
      ['ペットいる', '犬と猫どっち好き', 'Do you have pets'],
      ['ペット', '犬', '猫', '飼って'], {'pets', 'hobbies'}),
  _q('ask_books', 'Asks about books',
      ['本読む', '何の本が好き', 'Do you read books'],
      ['本', '読む', '小説', '好き'], {'books', 'hobbies'}),
];

ConversationIntentDefinition _q(
  String id,
  String description,
  List<String> examples,
  List<String> keywords,
  Set<String> tags, {
  int priority = 86,
}) =>
    _i(id, description, examples, keywords, ConversationFunction.question, tags,
        priority: priority);

ConversationIntentDefinition _r(
  String id,
  String description,
  List<String> examples,
  List<String> keywords,
  Set<String> tags,
) =>
    _i(
      id,
      description,
      examples,
      keywords,
      ConversationFunction.surprise,
      tags,
    );

ConversationIntentDefinition _v(
  String id,
  String description,
  List<String> examples,
  List<String> keywords,
  Set<String> tags, {
  int priority = 90,
}) =>
    _i(
      id,
      description,
      examples,
      keywords,
      ConversationFunction.invitation,
      tags,
      priority: priority,
    );

ConversationIntentDefinition _x(
  String id,
  String description,
  List<String> examples,
  List<String> keywords,
  Set<String> tags,
) =>
    _i(
      id,
      description,
      examples,
      keywords,
      ConversationFunction.softRejection,
      tags,
      priority: 94,
    );

ConversationIntentDefinition _t(
  String id,
  String description,
  List<String> examples,
  List<String> keywords,
  Set<String> tags, {
  int priority = 82,
}) =>
    _i(id, description, examples, keywords, ConversationFunction.tease, tags,
        priority: priority);

ConversationIntentDefinition _c(
  String id,
  String description,
  List<String> examples,
  List<String> keywords,
  Set<String> tags,
) =>
    _i(id, description, examples, keywords, ConversationFunction.interest, tags,
        priority: 62);

ConversationIntentDefinition _i(
  String id,
  String description,
  List<String> examples,
  List<String> keywords,
  ConversationFunction function,
  Set<String> tags, {
  int priority = 70,
}) {
  final expandedExamples = <String>[...examples];
  if (keywords.length >= 2) {
    expandedExamples.add('${keywords[0]}${keywords[1]}');
  }
  expandedExamples.add('${examples.first}ね');
  final hints = <String>{
    ...id.split('_'),
    ...tags,
    ...keywords.take(3),
    switch (function) {
      ConversationFunction.question => 'statement',
      ConversationFunction.compliment => 'comeback',
      ConversationFunction.tease => 'witty',
      ConversationFunction.invitation => 'agreement',
      ConversationFunction.softRejection => 'respectful',
      _ => 'friendly',
    },
  }..removeWhere((value) => value.length < 2);
  return ConversationIntentDefinition(
    id: id,
    description: description,
    examples: expandedExamples.take(5).toList(growable: false),
    keywords: keywords,
    function: function,
    contextTags: tags,
    responseHints: hints.take(10).toList(growable: false),
    priority: priority,
  );
}
