#!/usr/bin/env python3
"""Attaches Korean text and romanization to the starter library.

Runs after build_seed.py has assembled the 155 lines. It does not rewrite any
Japanese, any tag, any English meaning, or any id: it only adds a `translations`
map (with a 'ko' entry) and a `koreanRomanization` string to each line, then
re-emits the seed's two generated files.

## How Korean is matched to Japanese

The Korean source file mirrors the original LGData.txt section for section and
row for row, but carries no Japanese and no English for most lines - so the only
reliable join is *by the Japanese line itself*, recovered positionally:

  1. Parse LGData.txt and the Korean file in the same section order.
  2. Within each section, pair the nth Japanese line with the nth Korean line.
  3. Build japanese_text -> korean_text from those pairs.
  4. For each seed line, look up its japaneseText in that map.

154 of the 155 seed lines match their Japanese verbatim. The one exception is a
club line the seed reworded from its LGData original; it has an explicit
override below, keyed by the seed's Japanese so the match is exact and the
reason is on the record.

## Romanization

Generated by tool/korean_romanize.py (Revised Romanization with the sound
changes that alter the reading). A per-line override map handles anything the
rules get wrong; there is a report at the end of how many lines used one.
"""

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_seed  # noqa: E402  (populates build_seed.LINES on import)
import korean_romanize  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_HERE = os.path.dirname(os.path.abspath(__file__))


def _first_existing(paths):
    for path in paths:
        if os.path.exists(path):
            return path
    return paths[0]


# The Korean source and the Japanese reference are vendored into tool/data so
# CI - which has neither the uploads nor the project mount - can regenerate the
# seed. The mounted paths are kept as fallbacks for local runs.
KOREAN_FILE = os.environ.get('OPENCUE_KOREAN_FILE') or _first_existing([
    os.path.join(_HERE, 'data', 'korean_approach_lines.txt'),
    '/mnt/user-data/uploads/English_Korean_Approach_Lines.txt',
])
LGDATA_FILE = os.environ.get('OPENCUE_LGDATA_FILE') or _first_existing([
    os.path.join(_HERE, 'data', 'lgdata.txt'),
    '/mnt/project/LGData.txt',
])

# Seed lines whose Japanese was reworded from the LGData original and so cannot
# match by text. Keyed by the seed's japaneseText; value is the Korean line
# that corresponds by position and meaning. Kept tiny and explicit on purpose.
JAPANESE_TO_KOREAN_OVERRIDES = {
    # seed-club-08. LGData's line 14 in the club section,
    # "ここうるさすぎるから、名前だけ教えてください！", was shortened in the
    # seed to "名前だけ聞いてもいいですか？". Same intent, same slot.
    '名前だけ聞いてもいいですか？': '여기 너무 시끄러우니까 이름만 알려주세요!',
}

# Romanization overrides, keyed by Korean string, for readings the rule engine
# gets wrong. Empty for now; populated only with human-verified corrections.
ROMANIZATION_OVERRIDES = {}


def parse_sections(path):
    """Ordered list of (section_title, [native_line, ...]).

    Handles both the table rows (| line | ... |) and the bullet lists
    (* line) that the source files mix - graceful exits and the reusable
    formula are bullets, everything else is tables.
    """
    sections = []
    current = None
    for raw in open(path, encoding='utf-8'):
        heading = re.match(r'##\s+(.*)', raw)
        if heading:
            current = heading.group(1).strip()
            sections.append((current, []))
            continue
        if current is None:
            continue
        text = raw.strip()
        if text.startswith('|'):
            cells = [c.strip() for c in text.strip('|').split('|')]
            if cells and cells[0] and not set(cells[0]) <= set('-: ') \
                    and cells[0] != 'Line':
                sections[-1][1].append(cells[0])
        elif text.startswith('* ') or text.startswith('- '):
            sections[-1][1].append(text[2:].strip())
    return sections


def build_japanese_to_korean():
    """japanese_text -> korean_text, via positional section alignment."""
    ja = parse_sections(LGDATA_FILE)
    ko = parse_sections(KOREAN_FILE)
    if len(ja) != len(ko):
        raise SystemExit(
            'Section count differs: LGData has %d, Korean file has %d. '
            'The positional join is only safe when they march together.'
            % (len(ja), len(ko))
        )

    mapping = {}
    for (ja_title, ja_lines), (ko_title, ko_lines) in zip(ja, ko):
        if len(ja_lines) != len(ko_lines):
            raise SystemExit(
                'Row count differs in a section: "%s" has %d Japanese rows '
                'but "%s" has %d Korean rows. Refusing to guess the pairing.'
                % (ja_title, len(ja_lines), ko_title, len(ko_lines))
            )
        for j, k in zip(ja_lines, ko_lines):
            mapping.setdefault(j, k)
    return mapping


def main():
    ja_to_ko = build_japanese_to_korean()

    matched = 0
    missing = []
    override_used = 0
    roman_override_used = 0

    for line in build_seed.LINES:
        japanese = line['japaneseText']
        korean = ja_to_ko.get(japanese)
        if korean is None:
            korean = JAPANESE_TO_KOREAN_OVERRIDES.get(japanese)
            if korean is not None:
                override_used += 1
        if korean is None:
            missing.append((line['id'], japanese))
            continue

        roman, used = korean_romanize.romanize(
            korean, overrides=ROMANIZATION_OVERRIDES)
        if used:
            roman_override_used += 1

        # Additive only. The Japanese, English, tags and id are untouched;
        # translations and koreanRomanization are inserted next to them.
        line['translations'] = {'ko': korean}
        line['koreanRomanization'] = roman
        matched += 1

    total = len(build_seed.LINES)
    if missing:
        print('Korean coverage INCOMPLETE: %d of %d lines have no Korean.'
              % (len(missing), total))
        for line_id, japanese in missing:
            print('  - %s  %s' % (line_id, japanese))
        return 1

    # Re-emit both generated files with the enriched lines.
    payload = {
        'schemaVersion': 1,
        'app': 'OpenCue',
        'kind': 'starterLibrary',
        'lines': build_seed.LINES,
    }

    pretty = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=False)
    ref_path = os.path.join(ROOT, 'assets/sample/starter_library.json')
    with open(ref_path, 'w', encoding='utf-8') as handle:
        handle.write(pretty + '\n')

    compact = json.dumps(payload, ensure_ascii=False, separators=(',', ':'))
    if "'''" in compact or r"\'" in compact:
        print('Seed JSON contains a sequence that breaks the Dart raw string.')
        return 1

    dart_path = os.path.join(ROOT, 'lib/data/seed/starter_library.dart')
    with open(dart_path, 'w', encoding='utf-8') as handle:
        handle.write(build_seed.dart_header(total))
        handle.write("const String starterLibraryJson = r'''\n")
        handle.write(compact)
        handle.write("\n''';\n")

    print('Korean OK: %d of %d lines carry Korean + romanization.'
          % (matched, total))
    print('  japanese->korean overrides used: %d' % override_used)
    print('  romanization overrides used:     %d' % roman_override_used)
    return 0


if __name__ == '__main__':
    sys.exit(main())
